language: cpp

matrix:
  include:
    # Lua 5.3
    - env: LUA_VERSION=5.3.3 COMPILER=g++-4.8
      compiler: gcc
      addons:
        apt: {sources: ['ubuntu-toolchain-r-test'], packages: ['g++-4.8']}
    - env: LUA_VERSION=5.3.3 COMPILER=g++-4.9
      compiler: gcc
      addons:
        apt: {sources: ['ubuntu-toolchain-r-test'], packages: ['g++-4.9']}
    - env: LUA_VERSION=5.3.3 COMPILER=g++-5
      compiler: gcc
      addons:
        apt: {sources: ['ubuntu-toolchain-r-test'], packages: ['g++-5']}
    - env: LUA_VERSION=5.3.3 COMPILER=g++-6
      compiler: gcc
      addons:
        apt: {sources: ['ubuntu-toolchain-r-test'], packages: ['g++-6']}
    - env: LUA_VERSION=5.3.3 COMPILER=clang++-3.7
      compiler: clang
      addons:
        apt: {sources: ['llvm-toolchain-precise-3.7'], packages: ['clang-3.7']}
    - env: LUA_VERSION=5.3.3 COMPILER=clang++-3.8
      compiler: clang
      addons:
        apt: {sources: ['llvm-toolchain-precise-3.8'], packages: ['clang-3.8']}

    # Lua 5.2
    - env: LUA_VERSION=5.2.4 COMPILER=g++-4.8
      compiler: gcc
      addons:
        apt: {sources: ['ubuntu-toolchain-r-test'], packages: ['g++-4.8']}
    - env: LUA_VERSION=5.2.4 COMPILER=g++-4.9
      compiler: gcc
      addons:
        apt: {sources: ['ubuntu-toolchain-r-test'], packages: ['g++-4.9']}
    - env: LUA_VERSION=5.2.4 COMPILER=g++-5
      compiler: gcc
      addons:
        apt: {sources: ['ubuntu-toolchain-r-test'], packages: ['g++-5']}
    - env: LUA_VERSION=5.2.4 COMPILER=g++-6
      compiler: gcc
      addons:
        apt: {sources: ['ubuntu-toolchain-r-test'], packages: ['g++-6']}
    - env: LUA_VERSION=5.2.4 COMPILER=clang++-3.7
      compiler: clang
      addons:
        apt: {sources: ['llvm-toolchain-precise-3.7'], packages: ['clang-3.7']}
    - env: LUA_VERSION=5.2.4 COMPILER=clang++-3.8
      compiler: clang
      addons:
        apt: {sources: ['llvm-toolchain-precise-3.8'], packages: ['clang-3.8']}

    # Lua 5.1
    - env: LUA_VERSION=5.1.5 COMPILER=g++-4.8
      compiler: gcc
      addons:
        apt: {sources: ['ubuntu-toolchain-r-test'], packages: ['g++-4.8']}
    - env: LUA_VERSION=5.1.5 COMPILER=g++-4.9
      compiler: gcc
      addons:
        apt: {sources: ['ubuntu-toolchain-r-test'], packages: ['g++-4.9']}
    - env: LUA_VERSION=5.1.5 COMPILER=g++-5
      compiler: gcc
      addons:
        apt: {sources: ['ubuntu-toolchain-r-test'], packages: ['g++-5']}
    - env: LUA_VERSION=5.1.5 COMPILER=g++-6
      compiler: gcc
      addons:
        apt: {sources: ['ubuntu-toolchain-r-test'], packages: ['g++-6']}
    - env: LUA_VERSION=5.1.5 COMPILER=clang++-3.7
      compiler: clang
      addons:
        apt: {sources: ['llvm-toolchain-precise-3.7'], packages: ['clang-3.7']}
    - env: LUA_VERSION=5.1.5 COMPILER=clang++-3.8
      compiler: clang
      addons:
        apt: {sources: ['llvm-toolchain-precise-3.8'], packages: ['clang-3.8']}

cache:
  directories:
    - lua-$LUA_VERSION

before_install:
  - if [[ -n "$COMPILER" ]]; then export CXX=$COMPILER; fi

install:
  # Build Lua
  - test -e "lua-$LUA_VERSION/src" || (wget "http://www.lua.org/ftp/lua-$LUA_VERSION.tar.gz" && tar xvfz "lua-$LUA_VERSION.tar.gz")
  - pushd "lua-$LUA_VERSION/src"
  - test -e liblua-custom.a || make LUA_A=liblua-custom.a linux
  - export "LUA_SOURCE_PATH=$(pwd)"
  - popd

script:
  - make "LUA_LIBDIR=$LUA_SOURCE_PATH" "LUA_INCDIR=$LUA_SOURCE_PATH" LUA_LIBNAME=lua-custom all

addons:
  apt:
    packages:
      - make
      - wget
